### ISSUE TITLE
Says "Playing Game" instead of "Listening To"

### ISSUE THREAD

**Issue by evanperryg-old** [ultrasn0w/foo_drpc#11]
Says "Playing a Game" when it could say "Listening to Music" or something like that. Example of what I mean here: [Spotify](https://i.imgur.com/OhIj2p1.jpg) vs [foobar](https://i.imgur.com/yk329gD.jpg)

As a smaller detail, the Discord sidebar says "_Playing_ foobar2000" but with Spotify it shows "_Listening to_ Spotify." I'm not sure if this is something you can actually change, but it'd be neat.

**Comment by ultrasn0w** [comment]
Hey there, It's not possible 'yet'. Please read https://github.com/ultrasn0w/foo_drpc/issues/1
Closing, because it's kind of a duplicate.
