### ISSUE TITLE
newest foobar version doesn't recognize the plugin anymore

### ISSUE THREAD

**Issue by Gattxd** [ultrasn0w/foo_drpc#12]
![mr kraba](https://user-images.githubusercontent.com/41839237/43359590-d9048972-92a4-11e8-8743-440208ffeb4a.PNG)
ive tried downloading all 3 versions all get the same error

**Comment by ultrasn0w** [comment]
Hey there,
I'll recompile it with the latest SDK after the weekend.
Unable to test and confirm this right now.

**Comment by Gattxd** [comment]
ok nice, thanks

**Comment by ultrasn0w** [comment]
See #15 .
