### ISSUE TITLE
Song metadata delayed after skipping.

### ISSUE THREAD

**Issue by MinkiNTN** [ultrasn0w/foo_drpc#5]
First of all, I want to let you know that this is the best thing I've found in a while, and thank you for making it :) 

Now on to the "bug"

- Turn on everything, song data are appearing as normal.
- After listening to like a minute or two, I skipped to the next song.
- The next song is played, but the metadata got stuck on the skipped song.
- I finished or skip another song, the metadata changed to the previous song.

For example, if I'm listening to song A, then I skipped to song B, the displayed song is still song A, then after I skip or song B ends, song C play but song B get displayed. This continues until I stopped, then the metadata is corrected.

Some information:

- foo_drpc v 0.3
- foobar2000 v 1.3.16, and I'm playing in shuffle (tracks) mode
- Discord latest build (idk where to check for its version, but the changelog show Mar 7)

Feel free to let me know if you need additional logs, files, or if I'm messing something up :)

Still, thank you for the work, it still works fine when I'm not skipping songs XD

P.S : I did check back, and this lasted throughout the songs (2-3 mins songs)

**Comment by thxne** [comment]
I made a post about this same issue previously and the creator explained it. I don't think it's something that can be 'fixed'.

**Comment by ultrasn0w** [comment]
Hey there and glad you enjoy the plugin :)
You may want to read through https://github.com/ultrasn0w/foo_drpc/issues/3 .
No song change is 'skipped' in terms of sending it to Discord (only if it occurs faster than 0.42 seconds).

**Comment by ultrasn0w** [comment]
Fixed by #13
