### ISSUE TITLE
Icon Quality Improvement

### ISSUE THREAD

**Issue by NotTsunami** [ultrasn0w/foo_drpc#7]
Hey! Really enjoy the plugin. Thanks for your time and effort. It looks great, but in my opinion could be improved visually. The material outline play/pause buttons look much better at 18dp/dark:
https://material.io/icons/#ic_pause_circle_outline
https://material.io/icons/#ic_play_circle_outline

And the 2014 logo from Wikipedia looks great as well:
https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Foobar2000_logo_2014.png/1200px-Foobar2000_logo_2014.png

**Comment by ultrasn0w** [comment]
Thanks for the suggestions, I'll definitely take a look at the icons you provided here! 
And great you like the rest :)

**Comment by ultrasn0w** [comment]
Was this concern fixed by #15 ?
(It has been quite some time 😊)

**Comment by NotTsunami** [comment]
Only 6 years, just a small moment of time! Yeah, I would consider that PR to have addressed this issue sufficiently. Cheers!
