### ISSUE TITLE
Edge Case Where Foobar's Presence Never Disappears

### ISSUE THREAD

**Issue by NotTsunami** [ultrasn0w/foo_drpc#8]
If you close foobar2000 before setting a song, it will remain in that initialized presence even if you close foobar2000, but if a song is set and you close, it acts as normal.

**Comment by ultrasn0w** [comment]
I'll give it a look, thanks.

**Comment by NotTsunami** [comment]
It does have to set the initialization state first - but if you close it in between that and selecting a song, then it gets stuck. I've done it on occasion where I accidentally launch foobar, close it and then discord thinks I'm still in foobar.

**Comment by ultrasn0w** [comment]
Okay, that's very odd. If the associated process of a rich presence ends, discord should normally clear everything related.
I'll try to reproduce it during the next days.
Maybe I can fix that, I kind of have a solution in mind.

**Comment by NotTsunami** [comment]
Right? It might just be our order is funky, but I don't have access to my normal desktop to test right now.

**Comment by NotTsunami** [comment]
Have you been able to reproduce? I can always record a video too.

**Comment by ultrasn0w** [comment]
No, I havent been able to reproduce.
Yes, you can if you like to.

**Comment by NotTsunami** [comment]
Solved in latest version
