### ISSUE TITLE
Rich Presence doesn't update when loading foobar's playback state

### ISSUE THREAD

**Issue by ghost** [ultrasn0w/foo_drpc#9]
First of all, thank you for this useful little utility.

The problem here is is that this tool will not update what track you're playing as long as the option "Save playback state when closing foobar2000 and resume on next startup" is enabled within foobar. (Preferences > Playback > Other).
It'll fix itself when you fully stop and start playback again.

**Comment by ultrasn0w** [comment]
Thanks for reporting, that maybe an edge case I did not cover!

**Comment by ultrasn0w** [comment]
Probably fixed by #15
